apiVersion: apps/v1
kind: Deployment
metadata:
  name: tier2-deployment
  labels:
    app: tier2
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: tier2
  template:
    metadata:
      labels:
        app: tier2
    spec:
      containers:
        - name: second-tier
          image: winpakin/second-tier:0.0.1
          ports:
            - containerPort: 3002