apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcserv
  labels:
    app: grpcserv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpcserv
  template:
    metadata:
      labels:
        app: grpcserv
    spec:
      containers:
        - name: grpcserv
          image: winpakin/grpcserv:0.0.1
          ports:
            - containerPort: 5001 