apiVersion: v1
kind: Service
metadata:
  name: grpcserv-service
  labels:
    app: grpcserv-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5001
  selector:
    app: grpcserv