apiVersion: v1
kind: Service
metadata:
  name: sndserv-service
  labels:
    app: sndserv-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: sndserv
  