apiVersion: apps/v1
kind: Deployment
metadata:
  name: sndserv
  labels:
    app: sndserv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sndserv
  template:
    metadata:
      labels: 
        app: sndserv
    spec:
      containers:
        - name: sndserv
          image: winpakin/sndserv:0.0.1
          ports:
            - containerPort: 5000 