apiVersion: v1
kind: Service
metadata:
  name: testserv-service
  labels:
    app: testserv-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5002
  selector:
    app: testserv